version: '2'

services:
  #Find latest tictactoe image and run it
  server:
    #Using image known as tictactoe by kristofer15
    image: kristofer15/tictactoe:${GIT_COMMIT}
    ports:
      #Listen on the specified ports. Must include the one specified in run.js
      ['80:80']
    links:
      #Connect to a container known as db
      - "db:postgres"
    environment:
      PORT: "80"
      NODE_ENV: "production"
  #Find latest postgres database image and run it
  db:
    #Using image known as postgres
    image: postgres
    ports:
      #Listen on port 5432
      ['5432:5432']
    environment:
      #Set the password
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mysecretpassword'
